name: GITHUB_OUTPUT
on: push
jobs:
    share:
        runs-on: ubuntu-latest
        steps:
            - id: source
              run: echo "result=hello" >> "${GITHUB_OUTPUT}"
            - env:
                  RESULT: ${{  steps.source.outputs.result }}
              run: echo "{RESULT}"
