name: Log group
on: push
jobs:
    log:
        runs-on: ubuntu-latest
        steps:
            - run: |
                  echo "::group::Show environment variable"
                  printenv
                  echo "::endgroup::"
